### ISSUE TITLE
Segfault in handleSecTypeItalc

### ISSUE THREAD

**Issue by spaceone** [iTALC/italc#75]
```
(gdb) bt
#0  0x00007fd078d9ef6b in raise () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  <signal handler called>
#2  0x0000000000000000 in ?? ()
#3  0x00007fd07099fa24 in QHostInfo::localDomainName () at kernel/qhostinfo_unix.cpp:345
#4  0x00007fd052c311de in LocalSystem::User::loggedOnUser () at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/lib/src/LocalSystem.cpp:285
#5  0x00007fd052c2bd85 in ItalcVncConnection::handleSecTypeItalc (client=client@entry=0x7fd04c060860) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/lib/src/ItalcVncConnection.cpp:788
#6  0x00007fd052c2c175 in handleSecTypeItalc (client=client@entry=0x7fd04c060860) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/lib/src/ItalcVncConnection.cpp:871
#7  0x00007fd052c4f6cb in InitialiseRFBConnection (client=client@entry=0x7fd04c060860) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/ica/x11/libvncclient/rfbproto.c:1265
#8  0x00007fd052c50d15 in rfbInitConnection (client=0x7fd04c060860) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/ica/x11/libvncclient/vncviewer.c:253
#9  rfbInitClient (client=0x7fd04c060860, argc=<optimized out>, argv=<optimized out>) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/ica/x11/libvncclient/vncviewer.c:365
#10 0x00007fd052c2c2fa in ItalcVncConnection::doConnection (this=this@entry=0x7fd04c05e1a0) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/lib/src/ItalcVncConnection.cpp:571
#11 0x00007fd052c2c628 in ItalcVncConnection::run (this=0x7fd04c05e1a0) at /var/build/temp/tmp.aYCByandhG/pbuilder/italc-2.0.25/lib/src/ItalcVncConnection.cpp:526
#12 0x00007fd075b07d0b in QThreadPrivate::start (arg=0x7fd04c05e1a0) at thread/qthread_unix.cpp:307
#13 0x00007fd078d96b50 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#14 0x00007fd07824030d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

The line kernel/qhostinfo_unix.cpp:345 is part of the following code block:
```
332 QString QHostInfo::localDomainName()
333 {
334 #if !defined(Q_OS_VXWORKS)
335     resolveLibrary();
336     if (local_res_ninit) {
337         // using thread-safe version
338         res_state_ptr state = res_state_ptr(qMalloc(sizeof(*state)));
339         Q_CHECK_PTR(state);
340         memset(state, 0, sizeof(*state));
341         local_res_ninit(state);
342         QString domainName = QUrl::fromAce(state->defdname);
343         if (domainName.isEmpty())
344             domainName = QUrl::fromAce(state->dnsrch[0]);
345         local_res_nclose(state);
346         qFree(state);
347
348         return domainName;
349     }
```

Do you have any clue what might be happening here under QT4 / italc 2?

**Comment by tobydox** [comment]
As discussed via e-mail this seems to be a bug inside Qt and can be circumvented by using glibc functions instead.
